phosphor-ldap-conf: update nslcd.conf file with tls_cacertfile info
tls_cacertfile specifies the path to the X.509 certificate for
peer authentication.

Also updated the file with "tls_reqcert hard", to force the
behavior: if no certificate is provided, or a bad certificate
is provided, the session is immediately terminated.

Tested: tested using below given commands
1.curl -c cjar -b cjar -k -H "Content-Type: application/json" -X  POST -d \
  '{"data":[true,"ldaps://9.194.251.139/","cn=Sivas,dc=Corp,dc=ibm,dc=com",\
  "cn=Users,dc=Corp,dc=ibm,dc=com",  "Welcome3ibm!",\
  "xyz.openbmc_project.User.Ldap.Create.SearchScope.sub",\
  "xyz.openbmc_project.User.Ldap.Create.Type.ActiveDirectory"] \
}' https://$BMC_IP//xyz/openbmc_project/user/ldap/action/CreateConfig

2.curl -b cjar -k -H "Content-Type: application/json" -X PUT -d '{"data":true}'\
  https://$BMC_IP/xyz/openbmc_project/user/ldap/config/attr/SecureLDAP

3.curl -b cjar -k -H "Content-Type: application/json" -X PUT -d \
  '{"data":"ldap://9.194.251.136/"}' \
  https://$BMC_IP/xyz/openbmc_project/ldap/config/attr/LDAPServerURI

when "/etc/ssl/certs/Root-CA.pem" doesn't exist on target, we get below
given error(if we try to set SecureLDAP is true):

root@witherspoon-w5:~# Oct 17 08:03:04 witherspoon-w5 phosphor-ldap-conf[1799]:
LDAP server's CA certificate not provided
Oct 17 08:03:04 witherspoon-w5 phosphor-ldap-conf[1799]: The operation is not
allowed
...........................
..........................
Oct 17 08:03:04 witherspoon-w5 phosphor-ldap-conf[1799]:
xyz.openbmc_project.Common.Error.NotAllowed: The operation is not allowed
Oct 17 08:03:04 witherspoon-w5 phosphor-ldap-conf[1799]: The operation failed
internally.

when we try to set serverURI without the prefix "ldaps"
(ex:"ldap://9.194.251.139/), we get below given error(if we try to set
SecureLDAP is true):

Oct 17 08:10:24 witherspoon-w5 phosphor-ldap-conf[1799]: bad LDAPSURI
Oct 17 08:10:24 witherspoon-w5 phosphor-ldap-conf[1799]: Invalid argument was
given.
.............................
.............................
Oct 17 08:10:24 witherspoon-w5 phosphor-gevent[1262]:
DBusException: xyz.openbmc_project.Common.Error.InvalidArgument:
Invalid argument was given.

Change-Id: I56ffe8b08bb71307b4f2bfe9cf935b6113e4579a
Signed-off-by: Nagaraju Goruganti <ngorugan@in.ibm.com>
Signed-off-by: Deepak Kodihalli <dkodihal@in.ibm.com>
Signed-off-by: Nagaraju Goruganti <ngorugan@in.ibm.com>